### PR TITLE
add sonarqube analysis to the project

### PR DESCRIPTION
**Pull request by stranljip**
**Motivation:**
* automatically execute checks with SonarQube after each commit in CI

**Modification:**
* modified package.json to execute checks and added the necessary configuration

**Result:**
* SonarQubeChecks are executed automatically

### CODE REVIEW

**Comment by stranljip** [comment]
OK - I amended the commit. It seems that I can merge myself - should I do that or are you going to do that?

**Comment by femiadeyemi** [comment]
After reviewing the code, I still can answer the question, why do we need this? What are we trying to achieve?

**Comment by stranljip** [comment]
Hi @femiadeyemi - I sent you a note on Mattermost since I did not want to extend the discussion here.

**Comment by stranljip** [comment]
Hi @femiadeyemi - I completely messed up my fork. I will close this PR and setup things again before opening a new clean PR. :-/

**Pull request closed without merging**
